import Link from "next/link";
import { BiographyContent } from "@/components/a3lam/BiographyContent";
import { PersonPortrait } from "@/components/a3lam/PersonPortrait";
import type { PersonRecord } from "@/lib/domain/a3lam";
import type { FoundationMessages } from "@/lib/i18n/messages";

function statusLabel(status: PersonRecord["person"]["status"], copy: FoundationMessages) {
  return status === "draft" ? copy.adminDraft : status === "review" ? copy.adminReview : status === "published" ? copy.adminPublished : copy.adminArchived;
}

export function AdminPreview({ record, copy }: { record: PersonRecord; copy: FoundationMessages }) {
  const { person, categories, sources, timeline, education } = record;
  return <article className="admin-preview"><div className="admin-preview-banner"><span>{copy.adminPreviewTitle}</span><b className={`admin-status admin-status-${person.status}`}>{statusLabel(person.status, copy)}</b><span>{copy.adminPreviewDescription}</span></div><header className="admin-preview-hero"><PersonPortrait src={person.image} alt={person.nameArabic} initials={person.nameArabic.slice(0, 2)} tone="teal" className="admin-preview-portrait" /><div><p className="eyebrow">{categories.map((category) => category.name).join(" · ")}</p><h1>{person.nameArabic}</h1><p className="admin-preview-latin" dir="ltr">{person.name}</p><p className="hero-lede">{person.shortBio}</p></div></header><section className="admin-preview-section"><h2>{copy.profileOverview}</h2><BiographyContent value={person.biography} /></section><section className="admin-preview-section"><h2>{copy.profileFacts}</h2><dl className="admin-facts">{person.birthDate ? <><dt>{copy.profileBirth}</dt><dd>{person.birthDate}{person.birthPlace ? ` · ${person.birthPlace}` : ""}</dd></> : null}{person.deathDate ? <><dt>{copy.profileDeath}</dt><dd>{person.deathDate}{person.deathPlace ? ` · ${person.deathPlace}` : ""}</dd></> : null}<dt>{copy.profileOccupation}</dt><dd>{person.occupations.join(" · ") || "—"}</dd></dl></section>{timeline.length ? <section className="admin-preview-section"><h2>{copy.timelineLabel}</h2><ol className="admin-preview-list">{timeline.map((event) => <li key={event.id}><strong>{event.date} · {event.title}</strong><p>{event.description}</p></li>)}</ol></section> : null}{education.length ? <section className="admin-preview-section"><h2>{copy.educationLabel}</h2><ul className="admin-preview-list">{education.map((item) => <li key={item.id}><strong>{item.institution}</strong><p>{item.field} · {item.dateRange}</p><p>{item.description}</p></li>)}</ul></section> : null}<section className="admin-preview-section"><h2>{copy.sourcesLabel}</h2>{sources.length ? <ul className="admin-preview-sources">{sources.map((source) => <li key={source.id}><span>{source.title} · {source.publisher}</span><span dir="ltr">{source.url}</span></li>)}</ul> : <p>{copy.adminNoSources}</p>}</section><Link className="button button-quiet" href={`/admin/people/${encodeURIComponent(person.id)}`}>{copy.adminBackToEdit}</Link></article>;
}
