import { getSafePublicUrl } from "@/lib/media/public";

export const SITE_EXPERIENCE_RESOURCES = [
  "settings",
  "identity",
  "appearance",
  "homepage",
  "navigation",
  "footer",
  "seo",
  "profile_presentation",
] as const;
export type SiteExperienceResource = (typeof SITE_EXPERIENCE_RESOURCES)[number];

type Direction = "rtl" | "ltr";
type Language = "ar" | "en";
type SafeCta = { label: string; href: string };
type HomepageSectionKey = "hero" | "search" | "featured" | "categories" | "profiles" | "about" | "final_cta";

export type SiteSettings = { siteName: string; siteTagline: string; siteDescription: string; defaultLanguage: Language; defaultDirection: Direction; supportEmail: string; contactEmail: string };
export type SiteIdentity = { siteName: string; shortName: string; tagline: string; brandDescription: string; logoUrl: string; faviconUrl: string };
export type AppearanceSettings = { theme: "light"; typography: "arabic-editorial"; spacing: "comfortable" | "compact"; radius: "soft" | "sharp"; navigationStyle: "editorial" | "minimal"; cardStyle: "elevated" | "outlined"; buttonStyle: "solid" | "quiet"; heroStyle: "editorial" | "compact"; footerStyle: "editorial" | "minimal"; tokens: { primary: "teal" | "ink"; accent: "copper" | "sand"; surface: "paper" | "mist"; density: "comfortable" | "compact"; container: "wide" | "standard" } };
export type HomepageSettings = { hero: { eyebrow: string; title: string; subtitle: string; primary: SafeCta; secondary: SafeCta; imageUrl: string }; search: { title: string; placeholder: string; helperText: string }; featured: { sectionTitle: string; sectionDescription: string; selectedCategoryIds: string[]; selectedPersonIds: string[]; selectionMode: "latest" | "selected" }; profiles: { title: string; description: string; cta: SafeCta; visible: boolean }; categories: { title: string; description: string; displayMode: "grid" | "list"; itemLimit: number }; about: { title: string; description: string; visible: boolean }; finalCta: { title: string; description: string; button: SafeCta }; sections: { key: HomepageSectionKey; visible: boolean; order: number }[] };
export type NavigationItem = { id: string; label: string; href: string; kind: "internal" | "external"; visible: boolean; order: number };
export type NavigationSettings = { header: NavigationItem[]; footer: NavigationItem[] };
export type SocialLink = { platform: "linkedin" | "x" | "facebook" | "instagram" | "youtube" | "github" | "other"; label: string; url: string };
export type FooterGroup = { id: string; title: string; links: NavigationItem[] };
export type FooterSettings = { description: string; groups: FooterGroup[]; socialLinks: SocialLink[]; legalLinks: NavigationItem[]; copyright: string; contactHref: string };
export type SeoSettings = { siteTitle: string; defaultDescription: string; defaultKeywords: string[]; defaultOgImage: string; twitterCard: "summary" | "summary_large_image"; canonicalBase: string; indexingAllowed: boolean };
export type ProfilePresentationSettings = { templateId: "classic"; defaultSectionOrder: ("overview" | "skills" | "experience" | "education" | "certifications" | "languages" | "portfolio" | "files" | "source")[]; showPortfolio: boolean; showContactCta: boolean; showSocialLinks: boolean; showPrintButton: boolean; showShareControls: boolean };
export type SiteExperienceConfig = SiteSettings | SiteIdentity | AppearanceSettings | HomepageSettings | NavigationSettings | FooterSettings | SeoSettings | ProfilePresentationSettings;

const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
const text = (value: unknown, max: number, required = false): string => { if (typeof value !== "string" || value.length > max || (required && value.trim().length === 0)) throw new Error("Invalid site experience configuration"); return value.trim(); };
const bool = (value: unknown): boolean => { if (typeof value !== "boolean") throw new Error("Invalid site experience configuration"); return value; };
const oneOf = <T extends string>(value: unknown, values: readonly T[]): T => { if (typeof value !== "string" || !values.includes(value as T)) throw new Error("Invalid site experience configuration"); return value as T; };
const arrayOf = <T>(value: unknown, parser: (entry: unknown) => T, max: number): T[] => { if (!Array.isArray(value) || value.length > max) throw new Error("Invalid site experience configuration"); return value.map(parser); };
function safeUrl(value: unknown) { const candidate = text(value, 1_000); if (!candidate) return ""; if (candidate.startsWith("/") && !candidate.startsWith("//")) return candidate; if (getSafePublicUrl(candidate)) return candidate; throw new Error("Invalid site experience configuration"); }
function email(value: unknown) { const candidate = text(value, 320); if (!candidate || /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(candidate)) return candidate; throw new Error("Invalid site experience configuration"); }
function cta(value: unknown): SafeCta { if (!isRecord(value)) throw new Error("Invalid site experience configuration"); return { label: text(value.label, 100), href: safeUrl(value.href) }; }
function navigationItem(value: unknown): NavigationItem { if (!isRecord(value)) throw new Error("Invalid site experience configuration"); return { id: text(value.id, 80, true), label: text(value.label, 120, true), href: safeUrl(value.href), kind: oneOf(value.kind, ["internal", "external"] as const), visible: bool(value.visible), order: numberValue(value.order, 0, 50) }; }
function numberValue(value: unknown, min: number, max: number) { if (typeof value !== "number" || !Number.isInteger(value) || value < min || value > max) throw new Error("Invalid site experience configuration"); return value; }
function section(value: unknown): HomepageSettings["sections"][number] { if (!isRecord(value)) throw new Error("Invalid site experience configuration"); return { key: oneOf(value.key, ["hero", "search", "featured", "categories", "profiles", "about", "final_cta"] as const), visible: bool(value.visible), order: numberValue(value.order, 0, 20) }; }

function parseSettings(input: unknown): SiteSettings { if (!isRecord(input)) throw new Error("Invalid site experience configuration"); return { siteName: text(input.siteName, 120, true), siteTagline: text(input.siteTagline, 240), siteDescription: text(input.siteDescription, 500), defaultLanguage: oneOf(input.defaultLanguage, ["ar", "en"] as const), defaultDirection: oneOf(input.defaultDirection, ["rtl", "ltr"] as const), supportEmail: email(input.supportEmail), contactEmail: email(input.contactEmail) }; }
function parseIdentity(input: unknown): SiteIdentity { if (!isRecord(input)) throw new Error("Invalid site experience configuration"); return { siteName: text(input.siteName, 120, true), shortName: text(input.shortName, 60, true), tagline: text(input.tagline, 240), brandDescription: text(input.brandDescription, 500), logoUrl: safeUrl(input.logoUrl), faviconUrl: safeUrl(input.faviconUrl) }; }
function parseAppearance(input: unknown): AppearanceSettings { if (!isRecord(input) || !isRecord(input.tokens)) throw new Error("Invalid site experience configuration"); return { theme: oneOf(input.theme, ["light"] as const), typography: oneOf(input.typography, ["arabic-editorial"] as const), spacing: oneOf(input.spacing, ["comfortable", "compact"] as const), radius: oneOf(input.radius, ["soft", "sharp"] as const), navigationStyle: oneOf(input.navigationStyle, ["editorial", "minimal"] as const), cardStyle: oneOf(input.cardStyle, ["elevated", "outlined"] as const), buttonStyle: oneOf(input.buttonStyle, ["solid", "quiet"] as const), heroStyle: oneOf(input.heroStyle, ["editorial", "compact"] as const), footerStyle: oneOf(input.footerStyle, ["editorial", "minimal"] as const), tokens: { primary: oneOf(input.tokens.primary, ["teal", "ink"] as const), accent: oneOf(input.tokens.accent, ["copper", "sand"] as const), surface: oneOf(input.tokens.surface, ["paper", "mist"] as const), density: oneOf(input.tokens.density, ["comfortable", "compact"] as const), container: oneOf(input.tokens.container, ["wide", "standard"] as const) } }; }
function parseHomepage(input: unknown): HomepageSettings { if (!isRecord(input) || !isRecord(input.hero) || !isRecord(input.search) || !isRecord(input.featured) || !isRecord(input.profiles) || !isRecord(input.categories) || !isRecord(input.about) || !isRecord(input.finalCta)) throw new Error("Invalid site experience configuration"); const sections = arrayOf(input.sections, section, 7); if (sections.length !== 7 || new Set(sections.map(item => item.key)).size !== 7) throw new Error("Invalid site experience configuration"); return { hero: { eyebrow: text(input.hero.eyebrow, 160), title: text(input.hero.title, 220, true), subtitle: text(input.hero.subtitle, 500), primary: cta(input.hero.primary), secondary: cta(input.hero.secondary), imageUrl: safeUrl(input.hero.imageUrl) }, search: { title: text(input.search.title, 160, true), placeholder: text(input.search.placeholder, 180), helperText: text(input.search.helperText, 300) }, featured: { sectionTitle: text(input.featured.sectionTitle, 160, true), sectionDescription: text(input.featured.sectionDescription, 400), selectedCategoryIds: arrayOf(input.featured.selectedCategoryIds, item => text(item, 120, true), 30), selectedPersonIds: arrayOf(input.featured.selectedPersonIds, item => text(item, 120, true), 30), selectionMode: oneOf(input.featured.selectionMode, ["latest", "selected"] as const) }, profiles: { title: text(input.profiles.title, 160, true), description: text(input.profiles.description, 400), cta: cta(input.profiles.cta), visible: bool(input.profiles.visible) }, categories: { title: text(input.categories.title, 160, true), description: text(input.categories.description, 400), displayMode: oneOf(input.categories.displayMode, ["grid", "list"] as const), itemLimit: numberValue(input.categories.itemLimit, 1, 12) }, about: { title: text(input.about.title, 160, true), description: text(input.about.description, 500), visible: bool(input.about.visible) }, finalCta: { title: text(input.finalCta.title, 160, true), description: text(input.finalCta.description, 400), button: cta(input.finalCta.button) }, sections }; }
function parseNavigation(input: unknown): NavigationSettings { if (!isRecord(input)) throw new Error("Invalid site experience configuration"); return { header: arrayOf(input.header, navigationItem, 20), footer: arrayOf(input.footer, navigationItem, 30) }; }
function social(value: unknown): SocialLink { if (!isRecord(value)) throw new Error("Invalid site experience configuration"); return { platform: oneOf(value.platform, ["linkedin", "x", "facebook", "instagram", "youtube", "github", "other"] as const), label: text(value.label, 80, true), url: safeUrl(value.url) }; }
function group(value: unknown): FooterGroup { if (!isRecord(value)) throw new Error("Invalid site experience configuration"); return { id: text(value.id, 80, true), title: text(value.title, 100, true), links: arrayOf(value.links, navigationItem, 20) }; }
function parseFooter(input: unknown): FooterSettings { if (!isRecord(input)) throw new Error("Invalid site experience configuration"); return { description: text(input.description, 500), groups: arrayOf(input.groups, group, 10), socialLinks: arrayOf(input.socialLinks, social, 12), legalLinks: arrayOf(input.legalLinks, navigationItem, 12), copyright: text(input.copyright, 240), contactHref: safeUrl(input.contactHref) }; }
function parseSeo(input: unknown): SeoSettings { if (!isRecord(input)) throw new Error("Invalid site experience configuration"); return { siteTitle: text(input.siteTitle, 160, true), defaultDescription: text(input.defaultDescription, 500), defaultKeywords: arrayOf(input.defaultKeywords, item => text(item, 60, true), 20), defaultOgImage: safeUrl(input.defaultOgImage), twitterCard: oneOf(input.twitterCard, ["summary", "summary_large_image"] as const), canonicalBase: safeUrl(input.canonicalBase), indexingAllowed: bool(input.indexingAllowed) }; }
function parsePresentation(input: unknown): ProfilePresentationSettings { if (!isRecord(input)) throw new Error("Invalid site experience configuration"); const order = arrayOf(input.defaultSectionOrder, item => oneOf(item, ["overview", "skills", "experience", "education", "certifications", "languages", "portfolio", "files", "source"] as const), 9); if (order.length !== 9 || new Set(order).size !== 9) throw new Error("Invalid site experience configuration"); return { templateId: oneOf(input.templateId, ["classic"] as const), defaultSectionOrder: order, showPortfolio: bool(input.showPortfolio), showContactCta: bool(input.showContactCta), showSocialLinks: bool(input.showSocialLinks), showPrintButton: bool(input.showPrintButton), showShareControls: bool(input.showShareControls) }; }

export const siteExperienceDefaults: { settings: SiteSettings; identity: SiteIdentity; appearance: AppearanceSettings; homepage: HomepageSettings; navigation: NavigationSettings; footer: FooterSettings; seo: SeoSettings; profile_presentation: ProfilePresentationSettings } = {
  settings: { siteName: "أعلام", siteTagline: "موسوعة الشخصيات العربية", siteDescription: "منصة عربية لاكتشاف الشخصيات المؤثرة وفهم أثرها عبر ملفات منظمة ومصادر واضحة.", defaultLanguage: "ar", defaultDirection: "rtl", supportEmail: "", contactEmail: "" },
  identity: { siteName: "أعلام", shortName: "A3LAM", tagline: "موسوعة الشخصيات العربية", brandDescription: "منصة عربية لفهم أثر الأشخاص وصناعة المعرفة.", logoUrl: "", faviconUrl: "/icon.svg" },
  appearance: { theme: "light", typography: "arabic-editorial", spacing: "comfortable", radius: "soft", navigationStyle: "editorial", cardStyle: "elevated", buttonStyle: "solid", heroStyle: "editorial", footerStyle: "editorial", tokens: { primary: "teal", accent: "copper", surface: "paper", density: "comfortable", container: "wide" } },
  homepage: { hero: { eyebrow: "اكتشف أثر الشخصيات العربية", title: "أعلام — موسوعة الشخصيات العربية والسير المهنية", subtitle: "اكتشف الشخصيات العربية، وابحث عن المهنيين، وأنشئ سيرتك الذاتية في مساحة واحدة.", primary: { label: "أنشئ سيرتك الذاتية", href: "/profile/new" }, secondary: { label: "استكشف الأعلام", href: "/search" }, imageUrl: "" }, search: { title: "ابحث في أعلام", placeholder: "ابحث عن اسم، مهنة، أو مدينة...", helperText: "جرّب اسمًا أو مجالًا لاكتشاف ملفات موثقة." }, featured: { sectionTitle: "وجوهٌ تستحق أن تُعرف", sectionDescription: "تظهر هنا الملفات المنشورة بعد اجتياز التحقق التحريري وربط المعلومات بمصادرها.", selectedCategoryIds: [], selectedPersonIds: [], selectionMode: "latest" }, profiles: { title: "أنشئ حضورك المهني", description: "أنشئ ملفًا مهنيًا منظمًا وشاركه ضمن حدود الخصوصية التي تختارها.", cta: { label: "أنشئ سيرتك الذاتية", href: "/profile/new" }, visible: true }, categories: { title: "كل أثرٍ له سياقه", description: "تنقل بين المجالات لاكتشاف الأشخاص والأفكار والإنجازات ضمن سياقها المهني والثقافي.", displayMode: "grid", itemLimit: 6 }, about: { title: "الدقة قبل الكثرة", description: "ملفات منظمة، مصادر واضحة، ومراجعة بشرية قبل النشر.", visible: true }, finalCta: { title: "لديك معلومة موثوقة؟ اجعلها تصل.", description: "أعلام ينمو بالمصادر الدقيقة والتصحيحات المسؤولة.", button: { label: "اعرف المزيد", href: "/about" } }, sections: ["hero", "search", "featured", "categories", "profiles", "about", "final_cta"].map((key, order) => ({ key: key as HomepageSectionKey, visible: true, order })) },
  navigation: { header: [{ id: "home", label: "الرئيسية", href: "/", kind: "internal", visible: true, order: 0 }, { id: "people", label: "استكشف", href: "/search", kind: "internal", visible: true, order: 1 }, { id: "categories", label: "التصنيفات", href: "/categories", kind: "internal", visible: true, order: 2 }, { id: "about", label: "عن أعلام", href: "/about", kind: "internal", visible: true, order: 3 }], footer: [{ id: "search", label: "استكشف", href: "/search", kind: "internal", visible: true, order: 0 }, { id: "categories", label: "التصنيفات", href: "/categories", kind: "internal", visible: true, order: 1 }, { id: "profile", label: "أنشئ سيرتك الذاتية", href: "/profile/new", kind: "internal", visible: true, order: 2 }, { id: "about", label: "المشروع", href: "/about", kind: "internal", visible: true, order: 3 }, { id: "contact", label: "تواصل", href: "/contact", kind: "internal", visible: true, order: 4 }, { id: "privacy", label: "الخصوصية", href: "/privacy", kind: "internal", visible: true, order: 5 }] },
  footer: { description: "منصة عربية لفهم أثر الأشخاص وصناعة المعرفة.", groups: [], socialLinks: [], legalLinks: [], copyright: "© أعلام · موسوعة الشخصيات العربية", contactHref: "/contact" },
  seo: { siteTitle: "أعلام — موسوعة الشخصيات العربية", defaultDescription: "أعلام منصة عربية لاكتشاف الشخصيات المؤثرة وفهم أثرها عبر ملفات منظمة ومصادر واضحة.", defaultKeywords: ["أعلام", "الشخصيات العربية", "موسوعة عربية", "اليمن"], defaultOgImage: "", twitterCard: "summary", canonicalBase: "", indexingAllowed: true },
  profile_presentation: { templateId: "classic", defaultSectionOrder: ["overview", "skills", "experience", "education", "certifications", "languages", "portfolio", "files", "source"], showPortfolio: true, showContactCta: true, showSocialLinks: true, showPrintButton: true, showShareControls: true },
};

export function parseSiteExperienceConfig<R extends SiteExperienceResource>(resource: R, input: unknown): (typeof siteExperienceDefaults)[R] {
  const parsers = { settings: parseSettings, identity: parseIdentity, appearance: parseAppearance, homepage: parseHomepage, navigation: parseNavigation, footer: parseFooter, seo: parseSeo, profile_presentation: parsePresentation } as const;
  return parsers[resource](input) as (typeof siteExperienceDefaults)[R];
}

export function isSiteExperienceResource(value: string): value is SiteExperienceResource { return (SITE_EXPERIENCE_RESOURCES as readonly string[]).includes(value); }
